import pandas as pd

# --- Configuration ---
# The full, original products file (300MB version)
# Ensure this file exists and the path is correct.
ORIGINAL_PRODUCTS_FILE = "data/raw/products.csv"

# The mapping file generated by the 'create_category_mappings.py' script
CATEGORY_MAPPING_FILE = "data/processed/category_mapping.csv"

# The final, clean, and merged dataset ready for training
OUTPUT_PRODUCTS_FILE = "data/processed/products_cleaned.csv"

# --- Main Script ---

print("Applying category mappings to the main product dataset...")

# 1. Load the original, large products dataset
try:
    products_df = pd.read_csv(ORIGINAL_PRODUCTS_FILE)
except FileNotFoundError:
    print(f"Error: The product data file '{ORIGINAL_PRODUCTS_FILE}' was not found.")
    print("Please make sure you have the original, large product CSV in the 'data/raw/' directory.")
    exit()

print(f"Loaded {len(products_df)} products from the original dataset.")

# 2. Load the category mapping
try:
    mapping_df = pd.read_csv(CATEGORY_MAPPING_FILE)
except FileNotFoundError:
    print(f"Error: The mapping file '{CATEGORY_MAPPING_FILE}' was not found.")
    print("Please run 'create_category_mappings.py' first to generate the mapping.")
    exit()

print("Loaded category mapping file.")

# 3. Create a simple mapping dictionary for efficiency
# We only need the mapping from 'category_id' to 'merged_category_id'
id_to_merged_id = pd.Series(mapping_df.merged_category_id.values, index=mapping_df.category_id).to_dict()

# 4. Apply the mapping to the products DataFrame
print("Mapping original category IDs to new merged category IDs...")
# The .map() function is highly efficient for this task.
products_df['merged_category_id'] = products_df['category_id'].map(id_to_merged_id)

# 5. Handle products whose categories might not be in the mapping (optional but good practice)
unmapped_count = products_df['merged_category_id'].isnull().sum()
if unmapped_count > 0:
    print(f"Warning: Found {unmapped_count} products with no matching category. They will be dropped.")
    products_df.dropna(subset=['merged_category_id'], inplace=True)

# Convert the new ID to an integer
products_df['merged_category_id'] = products_df['merged_category_id'].astype(int)


# 6. Select and save the final columns
# We keep the essential columns and add our new merged category ID.
final_df = products_df[['asin', 'title', 'imgUrl', 'merged_category_id']]
final_df.to_csv(OUTPUT_PRODUCTS_FILE, index=False)

print("\nProcess Complete!")
print(f"Successfully created the final cleaned product file with {len(final_df)} products.")
print(f"File saved at: '{OUTPUT_PRODUCTS_FILE}'")

# --- Final Dataset Info ---
print("\n--- Final Dataset Info ---")
print(f"Number of products: {len(final_df)}")
print(f"Number of unique merged categories: {final_df['merged_category_id'].nunique()}")
print("\nDistribution of products per new category:")
print(final_df['merged_category_id'].value_counts().sort_index())
print("--------------------------")
